### ISSUE TITLE
请问“pass_ticket”这个参数是怎么获得的？

### ISSUE THREAD

**Issue by joyce677** [Xuenew/base-wechat-shipinhao#2]
def get_shipinghao(video_id,pass_ticket):

    url = "https://mp.weixin.qq.com/recweb/videolistapi?action=getvideoinfo&feed_id=finder_{video_id}&channelid=699001&pass_ticket={pass_ticket}".format(video_id=video_id,pass_ticket=pass_ticket)

这个视频号的函数video_id对应的是objectId，pass_ticket对应的是哪个参数呢？

**Comment by Xuenew** [comment]
在扫码登录的时候会有，全局
